ARG AIRFLOW_VERSION=3.1.5
ARG PYTHON_VERSION=3.11
FROM apache/airflow:${AIRFLOW_VERSION}-python${PYTHON_VERSION}

COPY constraints.txt requirements.txt requirements-airflow.txt /tmp/retailpulse/

RUN python -m venv /home/airflow/.retailpulse-venv \
    && /home/airflow/.retailpulse-venv/bin/pip install --no-cache-dir \
        -r /tmp/retailpulse/requirements-airflow.txt
