ARG AIRFLOW_VERSION=3.1.5
FROM apache/airflow:${AIRFLOW_VERSION}

COPY requirements.txt requirements-airflow.txt /tmp/retailpulse/

RUN python -m venv /home/airflow/.retailpulse-venv \
    && /home/airflow/.retailpulse-venv/bin/pip install --no-cache-dir \
        -r /tmp/retailpulse/requirements-airflow.txt
